name: JoaoQR CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/
      - name: Deploy to Host
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: $({secrets.SERVER_SSH_KEY})
          ARGS: "-rlgoDzvc -i"
          SOURCE: "src/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER: |
            sudo docker compose up --build --force-recreate
